//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblUserLoginID;
	protected global::System.Web.UI.WebControls.Label lblPassword;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblUserEmail;
	protected global::System.Web.UI.WebControls.Label lblUserRegDate;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
